version: '3.7'
services:
  # Database for all services
  postgres:
    image: postgres:15
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: your_database_name
      POSTGRES_USER: your_username
      POSTGRES_PASSWORD: your_password

  service-registry:
    image: service-registry
    build:
      context: ./service-registry
      dockerfile: Dockerfile
    environment:
      - eureka.client.serviceUrl.defaultZone=http://service-registry:8761/eureka/
      - server.connection-timeout=60000
    ports:
      - "8761:8761"
    networks:
      - app-network

  api-gateway:
    image: api-gateway
    restart: on-failure
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    environment:
      - eureka.client.serviceUrl.defaultZone=http://service-registry:8761/eureka/
      - server.connection-timeout=60000
    depends_on:
      - service-registry
    ports:
      - "8080:8080"
    networks:
      - app-network

  cart-service:
    image: cart-service
    restart: on-failure
    build:
      context: ./cart-service
      dockerfile: Dockerfile
    environment:
      - eureka.client.serviceUrl.defaultZone=http://service-registry:8761/eureka/
      - server.connection-timeout=60000
    depends_on:
      - service-registry
      - postgres
    ports:
      - "8081:8081"
    networks:
      - app-network

  order-service:
    image: order-service
    restart: on-failure
    build:
      context: ./order-service
      dockerfile: Dockerfile
    environment:
      - eureka.client.serviceUrl.defaultZone=http://service-registry:8761/eureka/
      - server.connection-timeout=60000
    depends_on:
      - service-registry
      - postgres
    ports:
      - "8082:8082"
    networks:
      - app-network

  payment-service:
    image: payment-service
    restart: on-failure
    build:
      context: ./payment-service
      dockerfile: Dockerfile
    environment:
      - eureka.client.serviceUrl.defaultZone=http://service-registry:8761/eureka/
      - server.connection-timeout=60000
    depends_on:
      - service-registry
      - postgres
    ports:
      - "8083:8083"
    networks:
      - app-network

  product-service:
    image: product-service
    restart: on-failure
    build:
      context: ./product-service
      dockerfile: Dockerfile
    environment:
      - eureka.client.serviceUrl.defaultZone=http://service-registry:8761/eureka/
      - server.connection-timeout=60000
    depends_on:
      - service-registry
      - postgres
    ports:
      - "8084:8084"
    networks:
      - app-network

  promotion-service:
    image: promotion-service
    restart: on-failure
    build:
      context: ./promotion-service
      dockerfile: Dockerfile
    environment:
      - eureka.client.serviceUrl.defaultZone=http://service-registry:8761/eureka/
      - server.connection-timeout=60000
    depends_on:
      - service-registry
      - postgres
    ports:
      - "8085:8085"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
